### ISSUE TITLE
Remove padding on .container

### ISSUE THREAD

**Issue by le717** [coffins/coffins.github.io#9]
[These lines here](https://github.com/coffins/coffins.github.io/blob/master/css/stylesheet.css#L40-L43).

![padding](https://cloud.githubusercontent.com/assets/3382464/6999277/057f4286-dbd2-11e4-9f00-faf134358844.png)

Yea...

**Comment by coffins** [comment]
Not bug, but feature. :P 
Nevertheless, thanks. I fixed this.
